-- Run only on the local fictional database. Every fixture and audit entry rolls back.
begin;
create function pg_temp.check_qol(ok boolean, label text) returns void language plpgsql as $$
begin if not coalesce(ok,false) then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
do $$
declare staff uuid; term uuid; c2 uuid; c10 uuid; sub uuid; sub2 uuid; learner uuid; ungraded uuid;
 scheme uuid; o1 uuid; o2 uuid; payload jsonb; rows jsonb; r jsonb; stamp text:=substr(gen_random_uuid()::text,1,8); i integer; old_count bigint;
begin
 select id into strict staff from public.profiles where role='ADMIN' and active limit 1;
 perform set_config('request.jwt.claim.sub',staff::text,true);
 perform pg_temp.check_qol(not has_function_privilege('anon','public.delete_record(text,uuid)','EXECUTE') and not has_function_privilege('anon','public.write_student_grades(uuid,uuid,jsonb,boolean)','EXECUTE') and not has_function_privilege('anon','public.list_students(jsonb)','EXECUTE'),'anonymous RPC access denied');
 term:=public.manage_record('terms',jsonb_build_object('academic_year',2026,'name','QOL-'||stamp,'active',false));
 c2:=public.manage_record('classes',jsonb_build_object('name','QOL-'||stamp||'-2','active',true));
 c10:=public.manage_record('classes',jsonb_build_object('name','QOL-'||stamp||'-10','active',true));
 sub:=public.manage_record('subjects',jsonb_build_object('code','QOL-'||stamp,'name_th','Test','name_en','Test','active',true));
 sub2:=public.manage_record('subjects',jsonb_build_object('code','QOL2-'||stamp,'name_th','Test2','name_en','Test2','active',true));
 select id into scheme from public.grade_schemes order by created_at limit 1;
 payload:=jsonb_build_object('subject_id',sub,'term_id',term,'grading_type','NUMERIC_GRADE','max_score',100,'credits',1,'scheme_id',scheme,'include_in_gpa',true,'pass_mode','AUTOMATIC','pass_threshold',60);
 perform pg_temp.check_qol(public.create_offerings(payload,array[c2,c10])=2,'create a subject for two classrooms');
 begin perform public.create_offerings(payload,array[c2,c10]); raise exception 'Duplicate accepted'; exception when unique_violation then null; end;
 perform pg_temp.check_qol((select count(*)=2 from public.subject_offerings where term_id=term),'duplicate batch leaves original offerings intact');
 perform public.create_offerings(payload||jsonb_build_object('subject_id',sub2),array[c2]);
 select id into o1 from public.subject_offerings where subject_id=sub and class_id=c2 and term_id=term;
 select id into o2 from public.subject_offerings where subject_id=sub2 and class_id=c2 and term_id=term;
 for i in 1..52 loop
  ungraded:=public.manage_record('students',jsonb_build_object('student_number','QOL-'||stamp||'-'||lpad(i::text,3,'0'),'first_name','Test','last_name','Student','term_id',term,'class_id',case when i<=51 then c2 else c10 end));
  if i=1 then learner:=ungraded; end if;
 end loop;
 r:=public.list_students(jsonb_build_object('term',term,'search','QOL-'||stamp,'sort','class','take',50));
 perform pg_temp.check_qol((r->>'total')::int=52 and jsonb_array_length(r->'rows')=50 and (r->'rows'->49->>'class_name')='QOL-'||stamp||'-2','class sorting occurs before first-page pagination');
 r:=public.list_students(jsonb_build_object('term',term,'search','QOL-'||stamp,'sort','class','take',50,'skip',50));
 perform pg_temp.check_qol(jsonb_array_length(r->'rows')=2 and (r->'rows'->0->>'class_name')='QOL-'||stamp||'-2' and (r->'rows'->1->>'class_name')='QOL-'||stamp||'-10','natural classroom order continues on page two');
 rows:=jsonb_build_array(jsonb_build_object('offering_id',o1,'version',0,'score','80','result',null),jsonb_build_object('offering_id',o2,'version',0,'score','200','result',null));
 begin perform public.write_student_grades(learner,term,rows); raise exception 'Invalid score accepted'; exception when raise_exception then if sqlerrm<>'Score outside allowed range' then raise; end if; end;
 perform pg_temp.check_qol(not exists(select 1 from public.student_grades where student_id=learner),'invalid subject rolls back the entire multi-subject save');
 rows:=jsonb_set(rows,'{1,score}','"75"');
 perform public.write_student_grades(learner,term,rows);
 perform pg_temp.check_qol((select count(*)=2 from public.student_grades where student_id=learner and state='DRAFT'),'save all subjects as drafts');
 begin perform public.delete_record('students',learner); raise exception 'Graded student deleted'; exception when raise_exception then if sqlerrm not like 'DEPENDENCIES:%' then raise; end if; end;
 begin perform public.delete_record('classes',c2); raise exception 'Linked class deleted'; exception when raise_exception then if sqlerrm not like 'DEPENDENCIES:%' then raise; end if; end;
 begin perform public.delete_record('terms',term); raise exception 'Linked term deleted'; exception when raise_exception then if sqlerrm not like 'DEPENDENCIES:%' then raise; end if; end;
 perform pg_temp.check_qol(exists(select 1 from public.students where id=learner),'graded students and linked academic records protected');
 select jsonb_agg(jsonb_build_object('offering_id',offering_id,'version',version)) into rows from public.student_grades where student_id=learner;
 perform pg_temp.check_qol(public.write_student_grades(learner,term,rows,true)=2,'publish the student subjects atomically');
 begin perform public.write_student_grades(learner,term,rows,false); raise exception 'Stale version accepted'; exception when serialization_failure then null; end;
 perform pg_temp.check_qol((select count(*)=2 from public.student_grades where student_id=learner and state='PUBLISHED'),'stale versions cannot partially unpublish');
 perform public.delete_record('students',ungraded);
 perform pg_temp.check_qol(not exists(select 1 from public.students where id=ungraded) and not exists(select 1 from public.enrollments where student_id=ungraded),'delete unused student and its enrollment');
 perform public.delete_record('offerings',(select id from public.subject_offerings where class_id=c10 and subject_id=sub and term_id=term));
 perform public.delete_record('classes',c10);
 ungraded:=public.manage_record('terms',jsonb_build_object('academic_year',2026,'name','EMPTY-'||stamp,'active',false));
 perform public.delete_record('terms',ungraded);
 ungraded:=public.manage_record('subjects',jsonb_build_object('code','EMPTY-'||stamp,'name_th','Empty','name_en','Empty'));
 perform public.delete_record('subjects',ungraded);
 ungraded:=public.manage_record('schemes',jsonb_build_object('name','EMPTY-'||stamp,'rules','[{"minimum":0,"points":0},{"minimum":50,"points":4}]'::jsonb));
 perform public.delete_record('schemes',ungraded);
 perform pg_temp.check_qol(not exists(select 1 from public.grade_scheme_rules where scheme_id=ungraded),'unused class, term, subject, offering and scheme deletion');
 begin perform public.save_grades(o1,jsonb_build_array(jsonb_build_object('student_id',learner,'version',2,'score','80','result',null))); raise exception 'Published edit accepted'; exception when raise_exception then if sqlerrm<>'PUBLISHED_LOCKED' then raise; end if; end;
 perform pg_temp.check_qol(not has_function_privilege('authenticated','public.save_grades_v1(uuid,jsonb)','EXECUTE'),'old grade save cannot bypass publication lock');
 perform pg_temp.check_qol(public.remove_record('students',learner)='archived','graded student removal preserves history');
 perform pg_temp.check_qol((select not active from public.students where id=learner) and (select count(*)=2 from public.student_grades where student_id=learner),'archived student and grades retained');
 perform public.manage_record('students',jsonb_build_object('id',learner,'student_number','QOL-'||stamp||'-001','first_name','Test','last_name','Student','term_id',term,'class_id',c2,'active',true,'roll_number',42));
 perform pg_temp.check_qol((select roll_number=42 from public.enrollments where student_id=learner and term_id=term),'roll number stored per enrollment');
 perform set_config('request.jwt.claim.sub','',true);
 begin perform public.delete_record('students',learner); raise exception 'Unauthenticated deletion accepted'; exception when insufficient_privilege then null; end;
 begin perform public.list_students('{}'); raise exception 'Unauthenticated listing accepted'; exception when insufficient_privilege then null; end;
 perform pg_temp.check_qol(true,'RPCs require an active staff profile');
end $$;
rollback;
