-- Local databases only. Fixtures, role changes and audit records all roll back.
begin;
create temp table scope_ids(k text primary key,v uuid);
grant select on scope_ids to authenticated;
create function pg_temp.scope_id(key text) returns uuid language sql as $$ select v from scope_ids where k=key $$;
create function pg_temp.scope_check(ok boolean,label text) returns void language plpgsql as $$ begin if not coalesce(ok,false) then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
create function pg_temp.scope_denied(statement text) returns void language plpgsql as $$ begin execute statement; raise exception 'Unauthorized operation succeeded'; exception when insufficient_privilege then null; end $$;
grant execute on function pg_temp.scope_id(text),pg_temp.scope_check(boolean,text),pg_temp.scope_denied(text) to authenticated;
do $$
declare k text; u uuid; tid uuid; ca uuid; cb uuid; sub uuid; sub2 uuid; scheme uuid; oa uuid; ob uuid; shared uuid; sa uuid; sb uuid; stamp text:=substr(gen_random_uuid()::text,1,8); p jsonb;
begin
 foreach k in array array['admin','a','b','unassigned','developer'] loop
  u:=gen_random_uuid(); insert into auth.users(id) values(u); insert into public.profiles(id,display_name,role) values(u,k,case k when 'admin' then 'ADMIN' when 'developer' then 'DEVELOPER' else 'TEACHER' end); insert into scope_ids values(k,u);
 end loop;
 perform set_config('request.jwt.claim.sub',pg_temp.scope_id('admin')::text,true);
 tid:=public.manage_record('terms',jsonb_build_object('academic_year',2026,'name','SCOPE-'||stamp));insert into scope_ids values('term',tid);
 ca:=public.manage_record('classes',jsonb_build_object('name','SCOPE-A-'||stamp));cb:=public.manage_record('classes',jsonb_build_object('name','SCOPE-B-'||stamp));
 insert into scope_ids values('class_a',ca);
 sub:=public.manage_record('subjects',jsonb_build_object('code','SCA-'||stamp,'name_th','A','name_en','A'));sub2:=public.manage_record('subjects',jsonb_build_object('code','SCB-'||stamp,'name_th','B','name_en','B'));
 select id into strict scheme from public.grade_schemes limit 1;
 p:=jsonb_build_object('subject_id',sub,'term_id',tid,'class_id',ca,'grading_type','NUMERIC_GRADE','max_score',100,'credits',1,'scheme_id',scheme,'include_in_gpa',true,'pass_mode','AUTOMATIC','pass_threshold',60);
 oa:=public.manage_record('offerings',p);ob:=public.manage_record('offerings',p||jsonb_build_object('class_id',cb));shared:=public.manage_record('offerings',p||jsonb_build_object('subject_id',sub2));
 insert into scope_ids values('oa',oa),('ob',ob),('shared',shared);
 sa:=public.manage_record('students',jsonb_build_object('student_number','SCA-'||stamp,'first_name','A','last_name','Example','term_id',tid,'class_id',ca));
 sb:=public.manage_record('students',jsonb_build_object('student_number','SCB-'||stamp,'first_name','B','last_name','Example','term_id',tid,'class_id',cb));insert into scope_ids values('sa',sa),('sb',sb);
 perform public.assign_teacher(pg_temp.scope_id('a'),oa,true);perform public.assign_teacher(pg_temp.scope_id('b'),ob,true);perform public.assign_teacher(pg_temp.scope_id('b'),shared,true);
 perform public.save_grades(shared,jsonb_build_array(jsonb_build_object('student_id',sa,'score',80,'version',0)));
end $$;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.scope_id('a')::text,true) is not null as identity_set;
select pg_temp.scope_check((select count(*)=1 from public.students),'Teacher A sees own classroom roster only');
select pg_temp.scope_check((select count(*)=1 from public.enrollments),'Teacher A sees own enrollments only');
select pg_temp.scope_check((select count(*)=1 from public.subject_offerings),'Teacher A sees assigned courses only');
select pg_temp.scope_check((select count(*)=0 from public.student_grades),'Same classroom does not grant another teacher course grades');
select pg_temp.scope_check((public.list_students(jsonb_build_object('term',pg_temp.scope_id('term')))->>'total')::int=1,'Roster RPC respects RLS');
select pg_temp.scope_check(jsonb_array_length(public.teacher_work(pg_temp.scope_id('term')))=1,'Dashboard respects assignment scope');
select pg_temp.scope_check(public.save_grades(pg_temp.scope_id('oa'),jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sa'),'score',77,'version',0)))=1,'Teacher A can save assigned grades');
select pg_temp.scope_denied(format('select public.save_grades(%L,%L::jsonb)',pg_temp.scope_id('ob'),jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sb'),'score',99,'version',0))));
select pg_temp.scope_denied(format('select public.publish_grades(%L,''[]'',true)',pg_temp.scope_id('shared')));
select pg_temp.scope_denied(format('select public.write_student_grades(%L,%L,%L::jsonb)',pg_temp.scope_id('sa'),pg_temp.scope_id('term'),jsonb_build_array(jsonb_build_object('offering_id',pg_temp.scope_id('shared'),'score',99,'version',1))));
select pg_temp.scope_check(true,'Other teacher writes, publish and student-profile batch denied');
select pg_temp.scope_denied(format('select public.assign_teacher(%L,%L,true)',pg_temp.scope_id('a'),pg_temp.scope_id('ob')));
select pg_temp.scope_denied('update public.profiles set role=''DEVELOPER'' where id=auth.uid()');
select pg_temp.scope_denied('insert into public.teacher_assignments(teacher_id,offering_id) select auth.uid(),id from public.subject_offerings');
select pg_temp.scope_check(true,'Self assignment and role elevation denied');
select pg_temp.scope_denied('select public.manage_record(''classes'',''{"name":"forbidden"}'')');
select pg_temp.scope_denied(format('select public.remove_record(''students'',%L)',pg_temp.scope_id('sb')));
select pg_temp.scope_denied(format('select public.delete_record(''students'',%L)',pg_temp.scope_id('sa')));
select pg_temp.scope_denied(format('select public.restore_record(''offerings'',%L)',pg_temp.scope_id('ob')));
select pg_temp.scope_denied(format('select public.import_students(''[]'',%L)',pg_temp.scope_id('term')));
select pg_temp.scope_denied('select public.create_offerings(''{}'',''{}''::uuid[])');
select pg_temp.scope_check(true,'School roster/catalog mutation RPCs require administrator');
select pg_temp.scope_check(not has_function_privilege('authenticated','public.save_grades_v1(uuid,jsonb)','execute') and not has_function_privilege('authenticated','public.manage_record_v1(text,jsonb)','execute'),'Legacy helpers cannot bypass new rules');
select set_config('request.jwt.claim.sub',pg_temp.scope_id('b')::text,true) is not null as identity_set;
select pg_temp.scope_check((select count(*)=2 from public.subject_offerings) and (select count(*)=1 from public.student_grades),'Teacher B sees own courses and no A grades');
select set_config('request.jwt.claim.sub',pg_temp.scope_id('unassigned')::text,true) is not null as identity_set;
select pg_temp.scope_check((select count(*)=0 from public.students) and (public.list_students('{}')->>'total')::int=0 and jsonb_array_length(public.teacher_work(pg_temp.scope_id('term')))=0,'Unassigned teacher has no student or grade access');
select set_config('request.jwt.claim.sub',pg_temp.scope_id('developer')::text,true) is not null as identity_set;
select pg_temp.scope_check(public.is_admin() and public.is_staff(),'Developer role has admin capabilities');
select public.assign_teacher(pg_temp.scope_id('a'),pg_temp.scope_id('oa'),false);
select set_config('request.jwt.claim.sub',pg_temp.scope_id('a')::text,true) is not null as identity_set;
select pg_temp.scope_check((select count(*)=0 from public.students),'Revocation immediately removes data access');
reset role;
rollback;
