-- Local databases only. Fixtures, role changes and audit records all roll back.
begin;
create temp table scope_ids(k text primary key,v uuid);
grant select on scope_ids to authenticated;
create function pg_temp.scope_id(key text) returns uuid language sql as $$ select v from scope_ids where k=key $$;
create function pg_temp.scope_check(ok boolean,label text) returns void language plpgsql as $$ begin if not coalesce(ok,false) then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
create function pg_temp.scope_denied(statement text) returns void language plpgsql as $$ begin execute statement; raise exception 'Unauthorized operation succeeded'; exception when insufficient_privilege then null; end $$;
grant execute on function pg_temp.scope_id(text),pg_temp.scope_check(boolean,text),pg_temp.scope_denied(text) to authenticated;
do $$
declare k text; u uuid; tid uuid; ca uuid; cb uuid; sub uuid; sub2 uuid; scheme uuid; oa uuid; ob uuid; shared uuid; sa uuid; sb uuid; stamp text:=substr(gen_random_uuid()::text,1,8); p jsonb;
begin
 foreach k in array array['admin','a','b','unassigned','developer'] loop
  u:=gen_random_uuid(); insert into auth.users(id) values(u); insert into public.profiles(id,display_name,role) values(u,k,case k when 'admin' then 'ADMIN' when 'developer' then 'DEVELOPER' else 'TEACHER' end); insert into scope_ids values(k,u);
 end loop;
 perform set_config('request.jwt.claim.sub',pg_temp.scope_id('admin')::text,true);
 tid:=public.manage_record('terms',jsonb_build_object('academic_year',2026,'name','SCOPE-'||stamp));insert into scope_ids values('term',tid);
 ca:=public.manage_record('classes',jsonb_build_object('name','SCOPE-A-'||stamp));cb:=public.manage_record('classes',jsonb_build_object('name','SCOPE-B-'||stamp));
 insert into scope_ids values('class_a',ca);
 sub:=public.manage_record('subjects',jsonb_build_object('code','SCA-'||stamp,'name_th','A','name_en','A'));sub2:=public.manage_record('subjects',jsonb_build_object('code','SCB-'||stamp,'name_th','B','name_en','B'));
 select id into strict scheme from public.grade_schemes limit 1;
 p:=jsonb_build_object('subject_id',sub,'term_id',tid,'class_id',ca,'grading_type','NUMERIC_GRADE','max_score',100,'credits',1,'scheme_id',scheme,'include_in_gpa',true,'pass_mode','AUTOMATIC','pass_threshold',60);
 oa:=public.manage_record('offerings',p);ob:=public.manage_record('offerings',p||jsonb_build_object('class_id',cb));shared:=public.manage_record('offerings',p||jsonb_build_object('subject_id',sub2));
 insert into scope_ids values('oa',oa),('ob',ob),('shared',shared);
 sa:=public.manage_record('students',jsonb_build_object('student_number','SCA-'||stamp,'first_name','A','last_name','Example','term_id',tid,'class_id',ca));
 sb:=public.manage_record('students',jsonb_build_object('student_number','SCB-'||stamp,'first_name','B','last_name','Example','term_id',tid,'class_id',cb));insert into scope_ids values('sa',sa),('sb',sb);
 perform public.assign_teacher(pg_temp.scope_id('a'),oa,true);perform public.assign_teacher(pg_temp.scope_id('b'),ob,true);perform public.assign_teacher(pg_temp.scope_id('b'),shared,true);
 perform public.save_grades(shared,jsonb_build_array(jsonb_build_object('student_id',sa,'score',80,'version',0)));
end $$;
create function pg_temp.reject(statement text, code text) returns void language plpgsql as $$ begin execute statement; raise exception 'Expected rejection';exception when others then if sqlstate<>code then raise;end if;end $$;
grant execute on function pg_temp.reject(text,text) to authenticated;
-- Additional rows in the same classroom verify neighbor order and future term preservation.
do $$ declare sid uuid;tid uuid;oid uuid;begin
 sid:=public.manage_record('students',jsonb_build_object('student_number','PILOT-'||substr(gen_random_uuid()::text,1,8),'first_name','Next','last_name','Student','term_id',pg_temp.scope_id('term'),'class_id',pg_temp.scope_id('class_a'),'roll_number',2));insert into scope_ids values('next',sid);
 update public.enrollments set roll_number=1 where student_id=pg_temp.scope_id('sa');
 tid:=public.manage_record('terms',jsonb_build_object('academic_year',2027,'name','OTHER-'||gen_random_uuid()));insert into scope_ids values('other_term',tid);
 insert into public.enrollments(student_id,term_id,class_id) values(pg_temp.scope_id('sa'),tid,pg_temp.scope_id('class_a'));
 insert into public.subject_offerings(subject_id,term_id,class_id,grading_type,max_score,credits,scheme_id,include_in_gpa) select subject_id,tid,class_id,grading_type,max_score,credits,scheme_id,include_in_gpa from public.subject_offerings where id=pg_temp.scope_id('oa') returning id into oid;insert into scope_ids values('other_offering',oid);
 perform public.save_grades(oid,jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sa'),'score',70,'version',0)));
 perform public.assign_homeroom(pg_temp.scope_id('unassigned'),pg_temp.scope_id('term'),pg_temp.scope_id('class_a'),true);
end $$;
-- The renamed legacy reservation helper is not called: qualified parameters must bind to the current function.
do $$ declare r jsonb;u uuid:=gen_random_uuid();begin
 perform public.issue_teacher_invite(repeat('d',64),1,1);
 r:=public.reserve_teacher_registration(repeat('d',64),'pilot.test','Pilot','Test','ครู','ทดสอบ');
 insert into auth.users(id,email,raw_app_meta_data) values(u,r->>'username',jsonb_build_object('school_registration',r->>'id'));
 perform pg_temp.scope_check((select official_first_name_th='ครู' and official_last_name_th='ทดสอบ' and role='TEACHER' and display_name='ครู ทดสอบ' from public.profiles where id=u),'Invite provisioning copies confirmed Thai names atomically');
end $$;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.scope_id('a')::text,true) is not null;
select pg_temp.scope_check((select count(*)=1 from public.subject_offerings),'Course teacher remains limited to assigned subject');
select pg_temp.scope_check((public.student_neighbors(pg_temp.scope_id('sa'),pg_temp.scope_id('term'))->>'next')::uuid=pg_temp.scope_id('next'),'Neighbor navigation follows roll order in authorized classroom');
select public.manage_record('students',jsonb_build_object('id',pg_temp.scope_id('sa'),'student_number','00-PILOT','first_name','Edited','last_name','Teacher','term_id',pg_temp.scope_id('term'),'class_id',pg_temp.scope_id('class_a'),'roll_number',1,'active',true));
select pg_temp.scope_check((select first_name='Edited' and student_number='00-PILOT' from public.students where id=pg_temp.scope_id('sa')),'Teacher updates identity while preserving leading zeroes');
select pg_temp.scope_denied(format('select public.manage_record(''students'',%L::jsonb)',jsonb_build_object('id',pg_temp.scope_id('sb'),'term_id',pg_temp.scope_id('term'),'class_id',pg_temp.scope_id('class_a'),'student_number','forbidden','first_name','X','last_name','Y')));
select pg_temp.scope_denied(format('select public.manage_record(''students'',%L::jsonb)',jsonb_build_object('id',pg_temp.scope_id('sa'),'pin','123456','term_id',pg_temp.scope_id('term'),'class_id',pg_temp.scope_id('class_a'))));
select pg_temp.scope_denied('select public.manage_record(''students'',''{}'')');
select pg_temp.scope_check(true,'Cross-class edits, PIN changes and student creation remain admin-only');
select public.save_grades(pg_temp.scope_id('oa'),jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sa'),'score',88,'version',0)));
select public.publish_grades(pg_temp.scope_id('oa'),jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sa'),'version',1)),true);
select pg_temp.reject(format('select public.clear_course_grades(%L,%L,1,''RESET'')',pg_temp.scope_id('oa'),pg_temp.scope_id('sa')),'40001');
select pg_temp.scope_check(public.clear_course_grades(pg_temp.scope_id('oa'),pg_temp.scope_id('sa'),2,'RESET')=1,'Reset removes published grade with current version');
select pg_temp.scope_denied(format('select public.clear_course_grades(%L,null,null,''RESET'',''[]'')',pg_temp.scope_id('shared')));
select pg_temp.scope_denied(format('select public.assign_homeroom(%L,%L,%L,true)',pg_temp.scope_id('a'),pg_temp.scope_id('term'),pg_temp.scope_id('class_a')));
select pg_temp.scope_denied(format('select public.purge_record(''students'',%L,''DELETE'')',pg_temp.scope_id('sa')));
select pg_temp.scope_check(true,'Teachers cannot reset other courses, assign themselves or purge central records');
select set_config('request.jwt.claim.sub',pg_temp.scope_id('unassigned')::text,true) is not null;
select pg_temp.scope_check((select count(*)=2 from public.subject_offerings) and (select count(*)=2 from public.students),'Homeroom sees all subjects and students in own class');
select pg_temp.scope_check(not public.can_access_offering(pg_temp.scope_id('ob')),'Homeroom does not widen to another classroom');
select pg_temp.reject(format('select public.clear_course_grades(%L,null,null,''RESET'',''[]'')',pg_temp.scope_id('shared')),'40001');
select pg_temp.scope_check(public.clear_course_grades(pg_temp.scope_id('shared'),null,null,'RESET',jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sa'),'version',1)))=1,'Bulk reset validates complete current snapshot');
select public.save_grades(pg_temp.scope_id('oa'),jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sa'),'score',65,'version',0)));
select pg_temp.scope_check(true,'Homeroom writes otherwise unassigned course');
select pg_temp.reject(format('select public.set_teacher_photo(%L)',pg_temp.scope_id('a')::text||'/avatar.jpg'),'42501');
select public.set_teacher_photo(auth.uid()::text||'/avatar.jpg');
select pg_temp.scope_check((select avatar_path=auth.uid()::text||'/avatar.jpg' from public.profiles where id=auth.uid()),'Photo path can only target own profile');
select set_config('request.jwt.claim.sub',pg_temp.scope_id('admin')::text,true) is not null;
select public.assign_homeroom(pg_temp.scope_id('unassigned'),pg_temp.scope_id('term'),(select class_id from public.subject_offerings where id=pg_temp.scope_id('ob')),true);
select set_config('request.jwt.claim.sub',pg_temp.scope_id('unassigned')::text,true) is not null;
select pg_temp.reject(format('select public.manage_record(''students'',%L::jsonb)',jsonb_build_object('id',pg_temp.scope_id('sa'),'student_number','00-PILOT','first_name','Edited','last_name','Teacher','term_id',pg_temp.scope_id('term'),'class_id',(select class_id from public.subject_offerings where id=pg_temp.scope_id('ob')))),'P0001');
select public.manage_record('students',jsonb_build_object('id',pg_temp.scope_id('sa'),'student_number','00-PILOT','first_name','Edited','last_name','Teacher','term_id',pg_temp.scope_id('term'),'class_id',(select class_id from public.subject_offerings where id=pg_temp.scope_id('ob')),'reset_on_move',true,'roll_number',1));
reset role;
select pg_temp.scope_check((select count(*)=0 from public.student_grades where student_id=pg_temp.scope_id('sa') and offering_id=pg_temp.scope_id('oa')) and (select count(*)=1 from public.student_grades where offering_id=pg_temp.scope_id('other_offering')),'Confirmed homeroom move resets selected term and preserves other term');
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.scope_id('b')::text,true) is not null;
select public.save_grades(pg_temp.scope_id('ob'),jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sb'),'score',90,'version',0)));
select public.publish_grades(pg_temp.scope_id('ob'),jsonb_build_array(jsonb_build_object('student_id',pg_temp.scope_id('sb'),'version',1)),true);
select public.submit_feedback('{"type":"OTHER","message":"Delete test","page":"","contact":""}');
select set_config('request.jwt.claim.sub',pg_temp.scope_id('admin')::text,true) is not null;
select pg_temp.scope_denied(format('select public.prepare_teacher_delete(%L,''DELETE'')',pg_temp.scope_id('admin')));
select public.prepare_teacher_delete(pg_temp.scope_id('b'),'DELETE');
select set_config('request.jwt.claim.sub',pg_temp.scope_id('b')::text,true) is not null;
select pg_temp.scope_check(not public.is_staff() and (select count(*)=0 from public.students),'Deleting teacher revokes existing session access immediately');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.scope_id('admin')::text,true) is not null;
delete from auth.users where id=pg_temp.scope_id('b');
select pg_temp.scope_check(not exists(select 1 from public.profiles where id=pg_temp.scope_id('b')) and not exists(select 1 from public.teacher_assignments where teacher_id=pg_temp.scope_id('b')) and not exists(select 1 from public.feedback where author=pg_temp.scope_id('b')),'Hard Auth delete cascades profile, assignments and feedback');
select pg_temp.scope_check((select score=90 and state='PUBLISHED' and updated_by is null from public.student_grades where offering_id=pg_temp.scope_id('ob') and student_id=pg_temp.scope_id('sb')),'Account deletion preserves published student grades');
select pg_temp.scope_check(not exists(select 1 from public.audit_logs where entity='profiles' and entity_id=pg_temp.scope_id('b') and (before_data is not null or after_data is not null) and action<>'DELETE'),'Deleted teacher profile has no audit backup');
set local role authenticated;
select public.archive_record('offerings',pg_temp.scope_id('ob'));
select pg_temp.scope_check((select archived from public.subject_offerings where id=pg_temp.scope_id('ob')) and (select count(*)=1 from public.student_grades where offering_id=pg_temp.scope_id('ob')),'Archive retains grades');
select public.restore_record('offerings',pg_temp.scope_id('ob'));
select public.purge_record('offerings',pg_temp.scope_id('ob'),'DELETE');
select pg_temp.scope_check(not exists(select 1 from public.subject_offerings where id=pg_temp.scope_id('ob')) and not exists(select 1 from public.student_grades where offering_id=pg_temp.scope_id('ob')),'Permanent course removal deletes archived/published dependencies');
select public.purge_record('students',pg_temp.scope_id('sa'),'DELETE');
select pg_temp.scope_check(not exists(select 1 from public.students where id=pg_temp.scope_id('sa')) and not exists(select 1 from public.enrollments where student_id=pg_temp.scope_id('sa')),'Permanent student removal includes all terms');
reset role;
select public.authorize_grade_reset(pg_temp.scope_id('admin'),pg_temp.scope_id('term'),repeat('e',64));
set local role authenticated;
select public.purge_record('terms',pg_temp.scope_id('term'),'DELETE');
select pg_temp.scope_check(not exists(select 1 from public.academic_terms where id=pg_temp.scope_id('term')) and exists(select 1 from public.students where id=pg_temp.scope_id('next')),'Permanent term removal retains student identities');
select pg_temp.reject(format('select public.purge_record(''classes'',%L,null)',pg_temp.scope_id('class_a')),'P0001');
do $$ declare sid uuid;oid uuid;scheme uuid;begin
 scheme:=public.manage_record('schemes',jsonb_build_object('name','PURGE-'||gen_random_uuid(),'rules','[{"minimum":80,"points":4},{"minimum":0,"points":0}]'::jsonb));
 sid:=public.manage_record('subjects',jsonb_build_object('code','PURGE-'||substr(gen_random_uuid()::text,1,8),'name_th','Purge','name_en','Purge'));
 oid:=public.manage_record('offerings',jsonb_build_object('subject_id',sid,'term_id',pg_temp.scope_id('other_term'),'class_id',pg_temp.scope_id('class_a'),'grading_type','NUMERIC_GRADE','max_score',100,'credits',1,'scheme_id',scheme,'include_in_gpa',true,'pass_mode','AUTOMATIC','pass_threshold',60));
 perform public.purge_record('schemes',scheme,'DELETE');
 perform pg_temp.scope_check(not exists(select 1 from public.grade_schemes where id=scheme) and not exists(select 1 from public.subject_offerings where id=oid),'Scheme purge removes dependent offerings and rules');
 perform public.purge_record('subjects',sid,'DELETE');
 perform public.purge_record('classes',pg_temp.scope_id('class_a'),'DELETE');
 perform pg_temp.scope_check(not exists(select 1 from public.classes where id=pg_temp.scope_id('class_a')),'Class purge succeeds after dependent history removal');
end $$;
reset role;
select pg_temp.scope_check(not has_function_privilege('anon','public.clear_course_grades(uuid,uuid,integer,text,jsonb)','execute') and not has_function_privilege('authenticated','public.reserve_teacher_registration_v2(text,text,text,text)','execute'),'Anonymous mutation and obsolete provisioning helpers denied');
rollback;
